map_config:
  map_file: ""
  map_dimension: 3

  # Initial position and orientation of the robot under the world frame
  init_x: 0.0
  init_y: 0.0
  init_z: 1.0
  init_yaw: 0.0

  map_size:
    # MARSIM PCD AABB: x[-17.24, 9.45], y[-30.88, 8.24], z[-3.62, 2.06]
    map_min_x: -19.0
    map_min_y: -33.0
    map_min_z: -4.0
    map_max_x: 11.0
    map_max_y: 10.0
    map_max_z: 3.0

    # Size of the task bbox in meters
    box_min_x: -15.0
    box_min_y: -29.0
    box_min_z: 0.0
    box_max_x: 8.0
    box_max_y: 7.0
    box_max_z: 2.2

    # Size of the visualization bbox in meters
    vbox_min_x: -17.0
    vbox_min_y: -31.0
    vbox_min_z: -0.2
    vbox_max_x: 9.0
    vbox_max_y: 8.0
    vbox_max_z: 2.5

  scale: 1.0

  T_b_c:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]

  T_m_w:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
